### ISSUE TITLE
Time formatting the x axis

### ISSUE THREAD

**Issue by RenatoUtsch** [sattarab/ng-nvd3#1]
How can I format the x axis with time format functions?
When I try to do this:

``` html
<nvd3-line-graph 
                data="data"
                objectEquality="true"
                chartId="chart"
                xformat="xFormatFunction()"
                xlabel="Tempo"
                ylabel="Referências"
                guide="true"
                height="500"
                width="1000"
                responsive="true">
            </nvd3-line-graph>
```

With the following xFormatFunction:

``` javascript
$scope.xformatFunction = function() {
    return function(d) {
        return d3.time.format("%H:%M")(new Date(d));
    };
};
```

The x axis gets populated with hexadecimal values, what is very strange.
How can I format the x axis by time?

**Comment by sattarab** [comment]
Will look into this and will get back to you in few days

**Comment by RenatoUtsch** [comment]
I fixed it by making xformat accept a function instead of just the format string.
If you want I can make a pull request.

**Comment by sattarab** [comment]
Yeah sure
